### PR TITLE
Added two functionalities to Debug Service : Class Info + Debug Ini

### PR DESCRIPTION
**Pull request by domangep**
The Class Info Debug Service allows to Browse PFC's Windows Contents and to navigate through Ancestors, properties, methods, events, etc. once activated, simply by clicking onto the red little red square that appeared in the upper left corner of any w_master descendant.

The Debug Ini Service allows to see content of the associated Application .INI file and also to modify keys value on the fly.
Simply, call gnv_app.inv_debug.of_OpenIni(True/false) to show/hide it.

### CODE REVIEW

**Comment by domangep** [comment]
Hello Everyone,
Can someone review this two additions to the n_cst_debug service ?
Thanks in advance,
Patrice

@bruce-armstrong , @mjl38 , @TABUllrich , @roberto924

**Comment by bruce-armstrong** [comment]
The soonest I’m going to have time to look at this won’t be until late tomorrow at best.

**Comment by bruce-armstrong** [comment]
There's 40 files in your pull request, much of it having nothing to do with your change.  Can you do a pull request which only includes the new and modified objects?

**Comment by domangep** [comment]
Ok, Bruce. I will close this pull request and come back with a new one containing only pertinent changes.

**Comment by domangep** [comment]
Hello Bruce,

I make multiple attempts to make a pull request containing only the 10
files I have modified or created to add the Debug Class Information & Debug
Ini Services, but unfortunately, GitHub still detects 44 files
modifications instead of 10 !
Do you have a specific technique to achieve this?

Thanks in advance,
Patrice

Le lun. 1 mars 2021 à 03:25, Bruce Armstrong <notifications@github.com> a
écrit :

**Comment by bruce-armstrong** [comment]
There's a couple of approaches.  One is to cherry pick the files for the PR

https://stackoverflow.com/questions/12660839/pull-request-for-only-certain-files-commits

However, what might be easier is to create another fork of the project, copy your current files into that new fork, and then do another commit from that new fork.  However, in that commit only select the files you directly added or modified (not the application objects, PBLs etc).  Then do a push and a pull request from the new fork.

https://stackoverflow.com/questions/28703140/pull-request-ignore-some-file-changes

**Pull request closed without merging**
